// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP1rLX6ZQosv4_6RDzNvU9F4YA9Z9vUPc',
    appId: '1:186026249077:web:ec5c14ba848912d2ada13c',
    messagingSenderId: '186026249077',
    projectId: 'sistema-ies-50b4b',
    authDomain: 'sistema-ies-50b4b.firebaseapp.com',
    storageBucket: 'sistema-ies-50b4b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIJn4j_2Rb2N7_-J1_nU36a9BU_9Ilf0A',
    appId: '1:186026249077:android:82df4d9ab73de090ada13c',
    messagingSenderId: '186026249077',
    projectId: 'sistema-ies-50b4b',
    storageBucket: 'sistema-ies-50b4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfg74zLvgHry02w49ZEyDvF1NHHZE-S3Q',
    appId: '1:186026249077:ios:f614d1e7a9f554cdada13c',
    messagingSenderId: '186026249077',
    projectId: 'sistema-ies-50b4b',
    storageBucket: 'sistema-ies-50b4b.appspot.com',
    iosClientId: '186026249077-ogo2vvn85j73qus2hlpuejl62hg4i8m9.apps.googleusercontent.com',
    iosBundleId: 'com.example.sistemaIes',
  );
}
